version: '3.9'

services:
  mongodatabase:
      image: mongo:7.0.14
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
        MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
  mongo-express:
    image: mongo-express:1.0.2-18
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_EXPRESS_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_EXPRESS_PASS
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_USER:$MONGO_PASS@mongodatabase:27017/
      ME_CONFIG_BASICAUTH: false
