FROM python:3.11-slim

WORKDIR /app

COPY challenge-final/consumer/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY challenge-final/consumer/. .

EXPOSE 8000

ENV FLASK_ENV=production

CMD ["python", "consumer.py"]